Force dumping of literal pool in functionTrampoline()
When LTO is enabled, the literal pool used by ARMv6-M & ARMv7-M
functionTrampoline() can be located very far away from the function. The
values are loaded with "ldr rX, =...", which uses PC-relative
addressing, so the allowed range is +/-4092. When the code is "big
enough", this causes the compilation to fail with:

-- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 --

/tmp/ccYIjL9l.s: Assembler messages:
/tmp/ccYIjL9l.s:39048: Error: offset out of range
lto-wrapper: fatal error: arm-none-eabi-g++ returned 1 exit status
compilation terminated.
/home/freddie/arm-none-eabi-gcc-7.1.0-170503/bin/../lib/gcc/arm-none-eabi/7.1.0/../../../../arm-none-eabi/bin/ld:
error: lto-wrapper failed
collect2: error: ld returned 1 exit status

-- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 --

Fix the problem by forcing the contents of the litaral pool to be dumped
right after the function.

This failure is observed for -O0 optimization and STM32F4DISCOVERY/test
configuration, with tup build only.