Use std::make_tuple(...) instead of {...} to fix build failure in GCC 5
../source/devices/memory/SdCard.cpp: In function 'std::tuple<int,
distortos::devices::{anonymous}::R1Response,
distortos::devices::{anonymous}::SdStatus>
distortos::devices::{anonymous}::executeAcmd13(distortos::devices::SynchronousSdMmcCardLowLevel&,
uint16_t, uint16_t)':
../source/devices/memory/SdCard.cpp:1250:51: error: converting to
'std::tuple<int, distortos::devices::{anonymous}::R1Response,
distortos::devices::{anonymous}::SdStatus>' from initializer list would
use explicit constructor 'constexpr std::tuple< <template-parameter-1-1>
>::tuple(_UElements&& ...) [with _UElements = {const int&, const
distortos::devices::{anonymous}::R1Response&,
distortos::devices::{anonymous}::SdStatus}; <template-parameter-2-2> =
void; _Elements = {int, distortos::devices::{anonymous}::R1Response,
distortos::devices::{anonymous}::SdStatus}]'
  return {ret.first, ret.second, SdStatus{sdStatus}};
                                                   ^
ninja: build stopped: subcommand failed.