Force dumping of literal pool in PendSV_Handler()
When LTO is enabled, the literal pool used by ARMv6-M & ARMv7-M
PendSV_Handler() can be located very far away from the function. The
values are loaded with "ldr rX, =...", which uses PC-relative
addressing, so the allowed range is +/-4092. When the code is "big
enough", this causes the compilation to fail with:

-- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 --

distortosTest.elf.ltrans2.s: Assembler messages:
distortosTest.elf.ltrans2.s:5926: Error: invalid offset, value too big
(0x00002DD0)
...
lto-wrapper: fatal error: arm-none-eabi-g++ returned 1 exit status
compilation terminated.
/home/freddie/arm-none-eabi-gcc-7.1.0-170503/bin/../lib/gcc/arm-none-eabi/7.1.0/../../../../arm-none-eabi/bin/ld:
error: lto-wrapper failed
collect2: error: ld returned 1 exit status

-- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 -- >8 --

Fix the problem by forcing the contents of the litaral pool to be dumped
right after the function.

This failure is observed for NUCLEO-F091RC/test configuration, with tup
build only.